#Configs for the GUI
showcase-title: §c§lTrophies
showcase-rows: 6

slots:
  default: DIRT
  0: RED_STAINED_GLASS_PANE
  1: BLUE_STAINED_GLASS_PANE
  2: LIME_STAINED_GLASS_PANE
  3: YELLOW_STAINED_GLASS_PANE
  4: ORANGE_STAINED_GLASS_PANE
  5: PURPLE_STAINED_GLASS_PANE
  6: GREEN_STAINED_GLASS_PANE
  7: BLACK_STAINED_GLASS_PANE
  8: WHITE_STAINED_GLASS_PANE
  9: GRAY_STAINED_GLASS_PANE
  10: RED_STAINED_GLASS_PANE
  11: BLUE_STAINED_GLASS_PANE
  12: LIME_STAINED_GLASS_PANE
  13: YELLOW_STAINED_GLASS_PANE
  14: ORANGE_STAINED_GLASS_PANE
  15: PURPLE_STAINED_GLASS_PANE
  16: GREEN_STAINED_GLASS_PANE
  17: BLACK_STAINED_GLASS_PANE
  18: WHITE_STAINED_GLASS_PANE
  19: GRAY_STAINED_GLASS_PANE
  20: RED_STAINED_GLASS_PANE
  21: BLUE_STAINED_GLASS_PANE
  22: LIME_STAINED_GLASS_PANE
  23: YELLOW_STAINED_GLASS_PANE
  24: ORANGE_STAINED_GLASS_PANE
  25: PURPLE_STAINED_GLASS_PANE
  26: GREEN_STAINED_GLASS_PANE
  27: BLACK_STAINED_GLASS_PANE
  28: WHITE_STAINED_GLASS_PANE
  29: GRAY_STAINED_GLASS_PANE
  30: RED_STAINED_GLASS_PANE
  31: BLUE_STAINED_GLASS_PANE
  32: LIME_STAINED_GLASS_PANE
  33: YELLOW_STAINED_GLASS_PANE
  34: ORANGE_STAINED_GLASS_PANE
  35: PURPLE_STAINED_GLASS_PANE
  36: GREEN_STAINED_GLASS_PANE
  37: BLACK_STAINED_GLASS_PANE
  38: WHITE_STAINED_GLASS_PANE
  39: GRAY_STAINED_GLASS_PANE
  40: RED_STAINED_GLASS_PANE
  41: BLUE_STAINED_GLASS_PANE
  42: LIME_STAINED_GLASS_PANE
  43: YELLOW_STAINED_GLASS_PANE
  44: ORANGE_STAINED_GLASS_PANE
  45: PURPLE_STAINED_GLASS_PANE
  46: GREEN_STAINED_GLASS_PANE
  47: BLACK_STAINED_GLASS_PANE
  48: WHITE_STAINED_GLASS_PANE
  49: GRAY_STAINED_GLASS_PANE
  50: RED_STAINED_GLASS_PANE
  51: BLUE_STAINED_GLASS_PANE
  52: LIME_STAINED_GLASS_PANE
  53: YELLOW_STAINED_GLASS_PANE